name: Docker Image CI

on:
  push:
    branches: [ "main", "trunk", "master", "workspace" ]
  pull_request:
    branches: [ "main", "trunk", "master", "workspace" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag slither-action:$(date +%s)
